language: java

notifications:
  email: false

cache:
  directories:
  - $HOME/.m2
  
before_install:
  - echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
  - sudo apt-get -qq update
  - sudo apt-get install -y git-lfs  
  - git lfs install

script:
#   - mvn test
