package ca.uleth.bugtriage.sibyl.utils;

import java.util.Properties;

import javax.mail.Address;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMessage.RecipientType;

import ca.uleth.bugtriage.sibyl.User;

public class EmailNotification {

	private static final String MAIL_SERVER = "smtp.cs.ubc.ca";

	private static final String FROM_ADDRESS = "sibyl-notifications@cs.ubc.ca";

	private static final String TO_ADDRESS = "janvik@cs.ubc.ca";

	private static final String SUBJECT_STRING = "Sibyl Notification - ";

	private static final String MESSAGE = "<This message was generated by a Sibyl event>\n\n";

	public static void send(String messageText){
		send(messageText, messageText);
	}
	
	public static void send(String subject, String messageText){
		try {
			Message message = setupMessage();
			message.setFrom(new InternetAddress(FROM_ADDRESS));
			message.addRecipient(Message.RecipientType.TO, new InternetAddress(TO_ADDRESS));
			message.setSubject(SUBJECT_STRING + subject);
			message.setText(MESSAGE + messageText);
			Transport.send(message);
		} catch (AddressException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (MessagingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private static Message setupMessage() {
		Properties props = new Properties();
		props.put("mail.smtp.host", MAIL_SERVER);
		Session session = Session.getDefaultInstance(props, null);
		return new MimeMessage(session);
	}
}
